### DISCUSSION TITLE
Disable specific streaming services

### DISCUSSION THREAD

**Discussion by rtrampox** [Seji64/SniDust#59] [Q&A] [answered]
Is there a way I can specify the service I want to proxy? I'd like to proxy only Netflix, and leave any other streaming unproxied.

**Comment by Seji64** [comment, marked as answer]
Possible, but a bit advanced - Here you go:


```
version: '3.8'
services:
    seji64:
        container_name: sniDust
        environment:
            - 'ALLOWED_CLIENTS=127.0.0.1/32, myDynDNSDomain.no-ip.com' # CHANGE THIS
            - 'EXTERNAL_IP=10.111.123.8' # CHANGE THIS TO YOUR VPS PUBLIC IP
            - TZ=Europe/Berlin
            - INSTALL_DEFAULT_DOMAINS=false
        ports:
            - '443:8443'
            - '80:8080'
            - '53:5300/udp'
            - '53:5300/tcp'
        image: 'ghcr.io/seji64/snidust:main'
        command: ["/bin/bash","-c","cp -v /var/lib/snidust/domains.d/05-netflix.lst /etc/snidust/domains.d/ && /entrypoint.sh"]
        restart: unless-stopped
```
