### ISSUE TITLE
iussue with changing upstream DNS

### ISSUE THREAD

**Issue by spencerwongfeilong** [Seji64/SniDust#50]
Hello 

below is my docker compose

```
version: '3.3'
services:
    snidust:
        container_name: snidust
        environment:
            - 'ALLOWED_CLIENTS=127.0.0.1'
            - 'EXTERNAL_IP=132.147.107.128'
            - SPOOF_ALL_DOMAINS=true # Set to true (case sensitive!) if you want to spoof ALL domains.
            - DNSDIST_UPSTREAM_POOL_NAME='customUpstream'
        ports:
            - 2443:8443
            - 380:8080
            - 653:5300/udp
        image: 'ghcr.io/publish3r/snidust-telerising:main'
        volumes:
          - /share/Container/SNIDUST/99-customUpstream.conf:/etc/dnsdist/conf.d/99-customUpstream.conf:ro
        restart: always
```
        
 When i mount 99-customUpstream.conf from my host, i get the follow error
 
 [INFO] [SniDust] Adding domain zatsslive-a.akamaihd.net to list
[INFO] [SniDust] Adding domain chromecast-receiver.zattoo.com to list
[INFO] [SniDust] Adding domain box30030.wemfbox.ch to list
[INFO] [SniDust] Adding domain zattoo.wemfbox.ch to list
[INFO] [SniDust] Adding domain zatsslive-a.akamaihd.net to list
[INFO] [SniDust] Adding domain zattoo.com to list
[INFO] [SniDust] *** End of Domain List ***
[INFO] [SniDust] *** Domain List: /etc/snidust/domains.d/10-yallo.lst***
[INFO] [SniDust] Adding domain y3o.tv to list
[INFO] [SniDust] Adding domain yallo.tv to list
[INFO] [SniDust] *** End of Domain List ***
[INFO] [SniDust] *** Complete! ***
Fatal Lua error: [string "chunk"]:17: Caught exception: [string "chunk"]:1: ')' expected near '='
stack traceback:
	[C]: in function 'includeDirectory'
	[string "chunk"]:17: in main chunk
