### ISSUE TITLE
PiHole + SniDust

### ISSUE THREAD

**Issue by EZarnosky** [Seji64/SniDust#8]
I have an OCI server and would love to have SniDust and PiHole on the same server. is there any way this can be done?

**Comment by Seji64** [comment]
Assuming OCI stands for Oracle Cloud Infrastructure (?) and you running pi-hole and SniDust with Docker you could probably doe something like this (not tested!):

```
version: "3.3"
services:
  snidust:
    environment:
      - ALLOWED_CLIENTS: "127.0.0.1, PUBLIC_ISP_IP"
      - EXTERNAL_IP: "PUBLIC_VPS_IP"
    ports:
      - "443:443"
      - "80:80"
      - "53:5300/udp"
    image: "ghcr.io/seji64/snidust:main"
  pihole:
  container_name: pihole
  image: pihole/pihole:latest
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "8080:80/tcp"
  environment:
    TZ: "America/Chicago"
    PIHOLE_DNS_: "snidust#5300"
  volumes:
    - "./etc-pihole:/etc/pihole"
    - "./etc-dnsmasq.d:/etc/dnsmasq.d"
  restart: unless-stopped

```
