### ISSUE TITLE
Timed out DNS connections

### ISSUE THREAD

**Issue by DTPlayer** [Seji64/SniDust#83]
Greetings. I ran into a problem that the DNS server does not process requests.

```
$ nslookup ifconfig.co 127.0.0.1
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
;; no servers could be reached
```

docker compose logs 
```
sniDust  | [INFO] [SniDust] *** End of Domain List ***
sniDust  | [INFO] [SniDust] *** Domain List: /etc/snidust/domains.d/10-yallo.lst***
sniDust  | [INFO] [SniDust] Adding domain y3o.tv to list
sniDust  | [INFO] [SniDust] Adding domain yallo.tv to list
sniDust  | [INFO] [SniDust] *** End of Domain List ***
sniDust  | [INFO] [SniDust] *** Domain List: /etc/snidust/domains.d/11-youtube.lst***
sniDust  | [INFO] [SniDust] Adding domain youtube.com to list
sniDust  | [INFO] [SniDust] Adding domain googlevideo.com to list
sniDust  | [INFO] [SniDust] Adding domain youtubei.googleapis.com to list
sniDust  | [INFO] [SniDust] Adding domain youtube.googleapis.com to list
sniDust  | [INFO] [SniDust] Adding domain youtube-nocookie.com to list
sniDust  | [INFO] [SniDust] Adding domain youtu.be to list
sniDust  | [INFO] [SniDust] Adding domain s.ytimg.com to list
sniDust  | [INFO] [SniDust] *** End of Domain List ***
sniDust  | [INFO] [SniDust] *** Complete! ***
sniDust  | Added downstream server 8.8.8.8:853
sniDust  | Added downstream server 8.8.4.4:853
sniDust  | Added downstream server 1.1.1.1:443
sniDust  | Added downstream server 1.0.0.1:443
sniDust  | Listening on 0.0.0.0:5300
sniDust  | ACL allowing queries from: 127.0.0.1/32
sniDust  | Console ACL allowing connections from: 127.0.0.0/8, ::1/128
sniDust  | Marking downstream cloudflare-dns (1.1.1.1:443) as 'up'
sniDust  | Marking downstream cloudflare-dns (1.0.0.1:443) as 'up'
sniDust  | Marking downstream dns.google (8.8.8.8:853) as 'up'
sniDust  | Marking downstream dns.google (8.8.4.4:853) as 'up'
sniDust  | ===================================================================
sniDust  | [INFO] SniDust started => Using 64.*.*.* - Point your DNS settings to this address
sniDust  | ===================================================================
```

docker-compose.yml
```
services:
    sniDust:
        container_name: sniDust
        environment:
            - 'ALLOWED_CLIENTS=127.0.0.1/32'
            - 'EXTERNAL_IP=64.*.*.*'
            - TZ=Europe/Berlin
        ports:
            - '443:8443'
            - '80:8080'
            - '53:5300/udp'
            - '53:5300/tcp'
        image: 'ghcr.io/seji64/snidust:main'
        restart: unless-stopped
```

Everything works well inside the container. What could be the problem when transferring everything from Docker to the system? Thank you in advance for your reply.
